In [1]:
import numpy as np
np.random.seed(1)

In [2]:
def relu(x):
    return (x>0)*x

In [3]:
def relu2deriv(output):
    return output > 0


In [4]:
alpha = 0.2
hidden_size = 4

In [5]:
streetlights = np.array([[1, 0, 1],
                         [0, 1, 1],
                         [0, 0, 1],
                         [1, 1, 1]])


In [6]:
walk_vs_stop = np.array([[1, 1, 0, 0]]).T


In [7]:
weight_0_1 = 2*np.random.random((3,hidden_size))-1
weight_1_2 = 2*np.random.random((hidden_size,1))-1

In [8]:
weight_0_1

array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
       [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
       [-0.20646505,  0.07763347, -0.16161097,  0.370439  ]])

In [9]:
weight_1_2

array([[-0.5910955 ],
       [ 0.75623487],
       [-0.94522481],
       [ 0.34093502]])

In [10]:
layer_0 = streetlights[0]
layer_1 = relu(np.dot(layer_0,weight_0_1))
layer_2 = np.dot(layer_1,weight_1_2)

In [11]:
relu(np.dot(layer_0, weight_0_1))[0]


-0.0

In [12]:
layer_2

array([0.39194327])

In [13]:
for iteration in range(60):
    layer_2_error = 0
    for i in range(len(streetlights)):
        layer_0 = streetlights[i:i+1]
        layer_1 = relu(np.dot(layer_0, weight_0_1))
        layer_2 = np.dot(layer_1, weight_1_2)
        layer_2_error+=np.sum((layer_2-walk_vs_stop[i:i+1])**2)
        layer_2_delta = (walk_vs_stop[i:i+1]-layer_2)
        layer_1_delta = layer_2_delta.dot(weight_1_2.T)*relu2deriv(layer_1)
        weight_1_2 += alpha*layer_1.T.dot(layer_2_delta)
        weight_0_1 += alpha*layer_0.T.dot(layer_1_delta)
    if(iteration%10==9):
        print("Error:"+ str(layer_2_error))


Error:0.6342311598444467
Error:0.35838407676317513
Error:0.0830183113303298
Error:0.006467054957103705
Error:0.0003292669000750734
Error:1.5055622665134859e-05
